In [1]:
import pandas as pd
import numpy as np

In [3]:
index = [('California', 2000),('California', 2010),('New York', 2000), ('New York', 2010),('Texas', 2000), ('Texas', 2010)]
populations = [33871648, 37253956,18976457, 19378102,20851820, 25145561]
pop = pd.Series(populations, index=index)
pop

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64

In [4]:
index = pd.MultiIndex.from_tuples(index)
index

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           )

In [5]:
pop = pop.reindex(index)
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [6]:
pop[:, 2010]

California    37253956
New York      19378102
Texas         25145561
dtype: int64

In [7]:
pop_df = pop.unstack()
pop_df

2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [8]:
pop_df.stack()

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [9]:
pop_df = pd.DataFrame({'total': pop, 'under18': [9267089, 9284094, 4687374, 4318033, 5906301, 6879014]})
pop_df

total  under18
California 2000  33871648  9267089
           2010  37253956  9284094
New York   2000  18976457  4687374
           2010  19378102  4318033
Texas      2000  20851820  5906301
           2010  25145561  6879014

In [10]:
f_u18 = pop_df['under18'] / pop_df['total']
f_u18.unstack()

2000      2010
California  0.273594  0.249211
New York    0.247010  0.222831
Texas       0.283251  0.273568

In [21]:
df = pd.DataFrame(np.random.rand(4, 2), index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
columns=['data1', 'data2'])
df

data1     data2
a 1  0.896446  0.109955
  2  0.882641  0.113842
b 1  0.883263  0.166987
  2  0.528831  0.638870

In [22]:
data = {('California', 2000): 33871648,
('California', 2010): 37253956,
('Texas', 2000): 20851820,
('Texas', 2010): 25145561,
('New York', 2000): 18976457,
('New York', 2010): 19378102}
pd.Series(data)

California  2000    33871648
            2010    37253956
Texas       2000    20851820
            2010    25145561
New York    2000    18976457
            2010    19378102
dtype: int64

In [23]:
pop.index.names = ['state', 'year']
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [43]:
index = pd.MultiIndex.from_product([[2013, 2014], [1, 2]], names=['year', 'visit'])
columns = pd.MultiIndex.from_product([['Bob', 'Guido', 'Sue'], ['HR', 'Temp']], names=['subject', 'type'])

In [64]:
data = np.round(np.random.randn(4, 6), 1)  #parantez içindeki 1 virgülden sonraki rakam sayısını gösterir.
data

array([[-0.7, -0.5, -0.4, -0.8,  0.1, -0.6],
       [ 0.5, -0.5, -1.2, -0.1, -0.1,  0.3],
       [ 1.1,  0.6, -0.6, -0.6,  2.5,  0.6],
       [-0.8,  0.8, -1.2,  0.5,  1.1, -0.4]])

In [65]:
data[:, ::2] *= 10
data

array([[ -7. ,  -0.5,  -4. ,  -0.8,   1. ,  -0.6],
       [  5. ,  -0.5, -12. ,  -0.1,  -1. ,   0.3],
       [ 11. ,   0.6,  -6. ,  -0.6,  25. ,   0.6],
       [ -8. ,   0.8, -12. ,   0.5,  11. ,  -0.4]])

In [66]:
data += 37
data

array([[30. , 36.5, 33. , 36.2, 38. , 36.4],
       [42. , 36.5, 25. , 36.9, 36. , 37.3],
       [48. , 37.6, 31. , 36.4, 62. , 37.6],
       [29. , 37.8, 25. , 37.5, 48. , 36.6]])

In [70]:
health_data = pd.DataFrame(data, index=index, columns=columns)
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      30.0  36.5  33.0  36.2  38.0  36.4
     2      42.0  36.5  25.0  36.9  36.0  37.3
2014 1      48.0  37.6  31.0  36.4  62.0  37.6
     2      29.0  37.8  25.0  37.5  48.0  36.6

In [71]:
health_data['Guido']

type          HR  Temp
year visit            
2013 1      33.0  36.2
     2      25.0  36.9
2014 1      31.0  36.4
     2      25.0  37.5

In [72]:
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [73]:
pop['California']

year
2000    33871648
2010    37253956
dtype: int64

In [74]:
pop['California', 2000]

33871648

In [75]:
pop.loc['California':'New York']

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
dtype: int64

In [76]:
pop[:, 2000]

state
California    33871648
New York      18976457
Texas         20851820
dtype: int64

In [77]:
pop[pop > 22000000]

state       year
California  2000    33871648
            2010    37253956
Texas       2010    25145561
dtype: int64

In [78]:
health_data['Guido', 'HR']

year  visit
2013  1        33.0
      2        25.0
2014  1        31.0
      2        25.0
Name: (Guido, HR), dtype: float64

In [79]:
health_data.iloc[:2, :2]

subject      Bob      
type          HR  Temp
year visit            
2013 1      30.0  36.5
     2      42.0  36.5

In [82]:
health_data.loc[:, ('Bob', 'HR')]

year  visit
2013  1        30.0
      2        42.0
2014  1        48.0
      2        29.0
Name: (Bob, HR), dtype: float64

In [83]:
health_data.loc[(:, 1), (:, 'HR')]

SyntaxError: invalid syntax (<ipython-input-83-fb34fa30ac09>, line 1)

In [84]:
idx = pd.IndexSlice
health_data.loc[idx[:, 1], idx[:, 'HR']]

subject      Bob Guido   Sue
type          HR    HR    HR
year visit                  
2013 1      30.0  33.0  38.0
2014 1      48.0  31.0  62.0

In [85]:
index = pd.MultiIndex.from_product([['a', 'c', 'b'], [1, 2]])
data = pd.Series(np.random.rand(6), index=index)
data.index.names = ['char', 'int']
data

char  int
a     1      0.660830
      2      0.451828
c     1      0.098754
      2      0.343081
b     1      0.870512
      2      0.410034
dtype: float64

In [86]:
data = data.sort_index()
data

char  int
a     1      0.660830
      2      0.451828
b     1      0.870512
      2      0.410034
c     1      0.098754
      2      0.343081
dtype: float64

In [87]:
data['a':'b']

char  int
a     1      0.660830
      2      0.451828
b     1      0.870512
      2      0.410034
dtype: float64

In [89]:
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [90]:
pop.unstack(level=0)

state  California  New York     Texas
year                                 
2000     33871648  18976457  20851820
2010     37253956  19378102  25145561

In [91]:
pop.unstack(level=1)

year            2000      2010
state                         
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [92]:
pop.unstack().stack()

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [94]:
pop.unstack().stack()

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [95]:
pop_flat = pop.reset_index(name='population')
pop_flat

state  year  population
0  California  2000    33871648
1  California  2010    37253956
2    New York  2000    18976457
3    New York  2010    19378102
4       Texas  2000    20851820
5       Texas  2010    25145561

In [96]:
pop_flat.set_index(['state', 'year'])

population
state      year            
California 2000    33871648
           2010    37253956
New York   2000    18976457
           2010    19378102
Texas      2000    20851820
           2010    25145561

In [97]:
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      30.0  36.5  33.0  36.2  38.0  36.4
     2      42.0  36.5  25.0  36.9  36.0  37.3
2014 1      48.0  37.6  31.0  36.4  62.0  37.6
     2      29.0  37.8  25.0  37.5  48.0  36.6

In [98]:
data_mean = health_data.mean(level='year')
data_mean

subject   Bob       Guido          Sue       
type       HR  Temp    HR   Temp    HR   Temp
year                                         
2013     36.0  36.5  29.0  36.55  37.0  36.85
2014     38.5  37.7  28.0  36.95  55.0  37.10

In [99]:
data_mean.mean(axis=1, level='type')

type    HR       Temp
year                 
2013  34.0  36.633333
2014  40.5  37.250000