In [2]:
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [4]:
len?

In [7]:
import math

In [43]:
math.sin(90)

0.8939966636005579

# A Python List Is More Than Just a List

In [16]:
L = list(range(10))

In [23]:
L2 = [str(s) for s in L]

In [20]:
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [26]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [31]:
L4=list(range(10))
A=array.array('i',L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
import numpy as np

In [33]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [34]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [42]:
np.array([1, 2, 3, 4], dtype='float32') #dizinin veri türünü açık bir şekilde ayarlamak için,dtype anahtar sözcüğünü kullan

array([1., 2., 3., 4.], dtype=float32)

In [41]:
np.array([range(i, i + 3) for i in [4, 4, 6]]) #iç içe geçmiş listeler çok boyutlu dizilerle sonuçlanır

array([[4, 5, 6],
       [4, 5, 6],
       [6, 7, 8]])

# Creating Arrays from Scratch

In [48]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [46]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [47]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [51]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [52]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [60]:
np.random.random((3, 3))

array([[0.41092812, 0.71994788, 0.34000566],
       [0.26558709, 0.71471973, 0.75890358],
       [0.75332782, 0.22805985, 0.15520342]])

In [61]:
np.random.normal(0, 1, (3, 3))

array([[-1.7467708 , -1.54363568, -0.34787408],
       [ 0.07404784, -0.905323  , -1.67380505],
       [ 1.15059877, -0.7770006 , -0.75050509]])

In [65]:
np.random.randint(0, 10, (3, 3))

array([[1, 3, 8],
       [5, 9, 5],
       [1, 6, 5]])