In [68]:
import numpy as np
np.random.seed(0) # 0 ve 1 arasındaki fark?

In [69]:
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3, 4))
x3 = np.random.randint(10, size=(3, 4, 5))

In [70]:
x1

array([5, 0, 3, 3, 7, 9])

In [71]:
print("dtype:", x2.dtype)

dtype: int32


In [72]:
x1

array([5, 0, 3, 3, 7, 9])

In [73]:
x2[2, -1]

7

In [74]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
x[5::-2]

array([5, 3, 1])

In [75]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [76]:
x2[:2,:3]

array([[3, 5, 2],
       [7, 6, 8]])

In [86]:
x2[::-1,::1]

array([[1, 6, 7, 7],
       [7, 6, 8, 8],
       [3, 5, 2, 4]])

In [88]:
print(x2[:, 0])

[3 7 1]


In [89]:
print(x2[0, :])

[3 5 2 4]


In [90]:
print(x2[0])

[3 5 2 4]


In [94]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Reshaping of Arrays

In [110]:
a = np.array([1, 2, 3])

In [111]:
a.reshape((1, 3))

array([[1, 2, 3]])

In [112]:
a.reshape((3,1))

array([[1],
       [2],
       [3]])

In [113]:
a[np.newaxis, :] #alternatif

array([[1, 2, 3]])

In [114]:
a[:,np.newaxis] #alternatif

array([[1],
       [2],
       [3]])

# Array Concatenation and Splitting

In [117]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [118]:
z = [99, 99, 99]
np.concatenate([x, y, z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [122]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [123]:
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [124]:
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [128]:
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [130]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

In [132]:
np.vstack([grid, x])

array([[9, 8, 7],
       [6, 5, 4],
       [1, 2, 3]])

In [133]:
y = np.array([[99],
              [99]])

In [134]:
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [140]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [1, 5])
print(x1, x2, x3)

[1] [ 2  3 99 99] [3 2 1]


In [141]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [145]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [146]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
