In [2]:
import numpy as np

In [43]:
L = np.random.random(100)
sum(L)

51.72234201955223

In [44]:
np.sum(L)

51.722342019552244

In [45]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)


180 ms ± 9.34 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.37 ms ± 69.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [46]:
min(big_array), max(big_array)

(1.0496175706364852e-08, 0.9999954689335151)

In [47]:
np.min(big_array), np.max(big_array)

(1.0496175706364852e-08, 0.9999954689335151)

In [48]:
%timeit min(big_array)
%timeit np.min(big_array)

107 ms ± 3.4 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
604 µs ± 20.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [49]:
M = np.random.random((3, 4))
print(M)

[[0.39906979 0.38691218 0.8529984  0.5961646 ]
 [0.87285351 0.04431951 0.7448978  0.02950006]
 [0.26094474 0.1694822  0.37999941 0.98359356]]


In [50]:
M.sum()

5.720735753149245

In [51]:
sum(M)

array([1.53286804, 0.60071389, 1.9778956 , 1.60925822])

In [52]:
M.min(axis=0)

array([0.26094474, 0.04431951, 0.37999941, 0.02950006])

In [55]:
M.max(axis=1)

array([0.8529984 , 0.87285351, 0.98359356])

In [59]:
%timeit np.sum(M)
%timeit M.sum()

5.03 µs ± 241 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
2.95 µs ± 229 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
