# Comparisons, Masks, and Boolean Logic

In [1]:
import numpy as np

In [6]:
rng = np.random.RandomState(0)
x = rng.randint(10, size=(3, 4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [7]:
x<6

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False]])

In [8]:
np.count_nonzero(x < 6)

8

In [9]:
np.sum(x<6)

8

In [12]:
np.sum(x < 6, axis=1)

array([4, 2, 2])

In [14]:
np.sum(x < 6, axis=0)

array([2, 2, 2, 2])

In [15]:
np.any(x > 8)

True

In [16]:
np.any(x < 0)

False

In [17]:
np.all(x < 10)

True

In [18]:
np.all(x == 6)

False

In [19]:
np.all(x < 8, axis=1)

array([ True, False,  True])

In [20]:
x[x<5]

array([0, 3, 3, 3, 2, 4])