In [2]:
import numpy as np

In [3]:
name = ['Alice', 'Bob', 'Cathy', 'Doug']
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 61.5]

In [6]:
x = np.zeros(4, dtype=int)
x

array([0, 0, 0, 0])

In [7]:
data = np.zeros(4, dtype={'names':('name', 'age', 'weight'), 'formats':('U10', 'i4', 'f8')})

In [8]:
print(data.dtype)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


In [9]:
data['name'] = name
data['age'] = age
data['weight'] = weight
print(data)

[('Alice', 25, 55. ) ('Bob', 45, 85.5) ('Cathy', 37, 68. )
 ('Doug', 19, 61.5)]


In [10]:
data['name']

array(['Alice', 'Bob', 'Cathy', 'Doug'], dtype='<U10')

In [11]:
data[0]

('Alice', 25, 55.)

In [12]:
data[-1]['name']

'Doug'

In [13]:
data[data['age'] < 30]['name']

array(['Alice', 'Doug'], dtype='<U10')

In [19]:
np.dtype({'names':('name', 'age', 'weight'), 'formats':((np.str_, 10), int, np.float32)}) #ya da aşağıdaki gibi

dtype([('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [21]:
np.dtype([('name', 'S10'), ('age', 'i4'), ('weight', 'f8')]) #tür adları önemli değilse aşağıdaki gibi

dtype([('name', 'S10'), ('age', '<i4'), ('weight', '<f8')])

In [16]:
np.dtype('S10,i4,f8')

dtype([('f0', 'S10'), ('f1', '<i4'), ('f2', '<f8')])

In [17]:
tp = np.dtype([('id', 'i8'), ('mat', 'f8', (3, 3))])
X = np.zeros(1, dtype=tp)
print(X[0])
print(X['mat'][0])

(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [22]:
data['age']

array([25, 45, 37, 19])