In [1]:
%config IPCompleter.greedy=True
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import OneHotEncoder

In [2]:
dataset=pd.read_excel('C:/Users/mert_/Desktop/uygulama_dersleri/Veriler/kredi_veriseti.xlsx')
dataset.head()

cinsiyet  yas  maas  kredi
0    Erkek   22  2200      0
1    Erkek   38  2300      0
2    Kadın   29  4600      0
3    Kadın   30  6000      0
4    Erkek   22  7900      0

In [3]:
one_hot= OneHotEncoder(handle_unknown='ignore')

In [4]:
one_hot_cinsiyet=one_hot.fit_transform(dataset['cinsiyet'].values.reshape(-1,1)).toarray()
one_hot_cinsiyet

array([[1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.

In [59]:
one_hot.categories_

[array(['Erkek', 'Kadın'], dtype=object)]

In [60]:
one_hot_df=pd.DataFrame(one_hot_cinsiyet,columns=one_hot.categories_)
one_hot_df.head()

Erkek Kadın
0   1.0   0.0
1   1.0   0.0
2   0.0   1.0
3   0.0   1.0
4   1.0   0.0

In [61]:
one_hot_df2=dataset.join(one_hot_df)
one_hot_df2.head()

cinsiyet  yas  maas  kredi  (Erkek,)  (Kadın,)
0    Erkek   22  2200      0       1.0       0.0
1    Erkek   38  2300      0       1.0       0.0
2    Kadın   29  4600      0       0.0       1.0
3    Kadın   30  6000      0       0.0       1.0
4    Erkek   22  7900      0       1.0       0.0

In [62]:
one_hot_df2.drop('cinsiyet',axis=1,inplace=True)
one_hot_df2.head()

yas  maas  kredi  (Erkek,)  (Kadın,)
0   22  2200      0       1.0       0.0
1   38  2300      0       1.0       0.0
2   29  4600      0       0.0       1.0
3   30  6000      0       0.0       1.0
4   22  7900      0       1.0       0.0

In [73]:
X=one_hot_df2.drop('kredi',axis=1)
y=one_hot_df2['kredi']

In [83]:
X

yas  maas  (Erkek,)  (Kadın,)
0     22  2200       1.0       0.0
1     38  2300       1.0       0.0
2     29  4600       0.0       1.0
3     30  6000       0.0       1.0
4     22  7900       1.0       0.0
..   ...   ...       ...       ...
395   49  4400       0.0       1.0
396   54  2600       1.0       0.0
397   53  2300       0.0       1.0
398   39  3600       1.0       0.0
399   52  3900       0.0       1.0

[400 rows x 4 columns]

In [74]:
from sklearn.model_selection import train_test_split

In [75]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [76]:
from sklearn.preprocessing import MinMaxScaler,StandardScaler

In [77]:
sc=StandardScaler()

In [78]:
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)

In [79]:
model=LogisticRegression(random_state=0)

In [81]:
model.fit(X_train,y_train)

LogisticRegression(random_state=0)

In [84]:
y_pred=model.predict(X_test)

In [85]:
y_pred

array([0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0],
      dtype=int64)

In [87]:
y_test.values

array([0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0],
      dtype=int64)

In [95]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [89]:
confusion_matrix(y_test,y_pred)

array([[78,  2],
       [19, 33]], dtype=int64)

In [94]:
classification_report(y_test,y_pred)

'              precision    recall  f1-score   support\n\n           0       0.80      0.97      0.88        80\n           1       0.94      0.63      0.76        52\n\n    accuracy                           0.84       132\n   macro avg       0.87      0.80      0.82       132\nweighted avg       0.86      0.84      0.83       132\n'

In [96]:
accuracy_score(y_test,y_pred)

0.8409090909090909