In [4]:
import numpy as np
np.arange(5) / np.arange(1,6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [5]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [13]:
x=np.arange(9).reshape((3,3))
2**x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]], dtype=int32)

In [56]:
L=np.random.random((3,4))
print(L)
print(np.sum(L))
print(np.min(L))
print(L.min(axis=0))
print(L.min(axis=1))
print(np.argmin(L))

[[0.97072364 0.08511974 0.4383983  0.36102976]
 [0.95680197 0.32495804 0.26286568 0.80174665]
 [0.44299495 0.7289688  0.61845759 0.25272651]]
6.2447916389109475
0.08511974462573046
[0.44299495 0.08511974 0.26286568 0.25272651]
[0.08511974 0.26286568 0.25272651]
1
